# Generated by Django 4.2.7 on 2024-01-16 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myalbum',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.musicians', verbose_name='Musician'),
        ),
    ]
